### ISSUE TITLE
请问剩下的缓存数据什么时候开放呢？

### ISSUE THREAD

**Issue by hackerchenzhuo** [wangxw5/wikiDiverse#2]
现有的数据无法支撑任何实验/验证。加起来不到3M..

**Comment by wangxw5** [comment]
Hi, 剩余的数据因为规模比较大，都在内网上，经过数据披露审批流程后就会放出。

**Comment by hackerchenzhuo** [comment]
好的谢谢，请问有具体时间吗？或者大概时间

**Comment by hackerchenzhuo** [comment]
已经三个多月了

**Comment by wangxw5** [comment]
Hi, 因为这次的数据规模比较大，我需要一个一个下到电脑上，然后传到google drive上，所以比较慢哈，还请你理解~这周末前会放出已经完成流程的数据。

**Comment by hackerchenzhuo** [comment]
谢谢同学，感谢你的回复。

- The data with retrieved 10 cands: to be released.
- The Wikipedia data: to be released.
- The image files: to be released.

请问这三部分的数据，和对 The Wikipedia data 进行Candidate Retrieval 操作的代码都会开放嘛？

**Comment by wangxw5** [comment]
Hi同学，感谢你的关注呀。
上面三个数据已经公布了部分了，原始的wikipedia数据正在走数据披露流程，但是抽取出的图片和文本信息已经公布了。
召回候选实体的阶段，由于数据量巨大，为了加速我使用了公司内部工具，所以目前无法公布代码。但是我正在开发一份无需内部工具的代码，完成后会进行分享。完成了新代码的测试后，benchmark代码也会一同放出。
非常抱歉的是，百度云链接目前无法提供，因为公司不允许在电脑上安装这类软件。
